server:
  port: 8081
  address: localhost
  servlet:
    context-path: /artifacts

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

plugins:
  pacakge-name: artifacts
  wecube-platform-server-url: http://localhost:8080/platform
  wecube-platform-token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJIVFRQLU1PQ0siLCJpYXQiOjE1NzYwNTMxOTcsInR5cGUiOiJhY2Nlc3NUb2tlbiIsImNsaWVudFR5cGUiOiJTVUJfU1lTVEVNIiwiZXhwIjoxNjAxOTczMTk3LCJhdXRob3JpdHkiOiJbU1VCX1NZU1RFTV0ifQ.Wd5rhFX3G-dtqlqYzgnkzd9i8T0xJkkPQSAckzO3V3NWXMCw3B9JWe7JlMjbNtE7va8qce1qcrz6qaa4pB0t5A

  wecmdb-server-url: http://localhost:18080/wecmdb

  saltstack-server-url: http://localhost:8082

  artifacts-s3-server-url: http://localhost:9000
  artifacts-s3-access-key: access_key
  artifacts-s3-secret-key: secret_key
